server:
  port: 8081

spring:
  application:
    name: clientes-service
  datasource:
    url: jdbc:postgresql://localhost:5433/clientesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  threads:
    virtual:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
